---
- hosts: all
  pre_tasks:
    - name: Set correct sudoers entry for Vagrant
      lineinfile: "dest=/etc/sudoers.d/vagrant state=present create=yes regexp='^%vagrant ' line='%vagrant ALL=(ALL) NOPASSWD: ALL' validate=
'visudo -cf %s'"

    - name: Add midonet repositories
      include: roles/midonet/tasks/repositories.yml

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=7200


- hosts: nsdb
  tags:
