---

- hosts: all
  pre_tasks:
    - name: Set correct sudoers entry for Vagrant
      lineinfile: "dest=/etc/sudoers.d/vagrant state=present create=yes regexp='^%vagrant ' line='%vagrant ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"

    - name: Add midonet repositories
      include: repositories.yml

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=7200

    - name: Create a loop interface to host NSDB
      shell:  ifconfig lo:2 "{{ NSDB_HOST }}" netmask 255.255.255.0 up

    - name: Enable ip routing
      shell:  sysctl -w net.ipv4.ip_forward=1

  roles:
    - role: zookeeper
      listen_address: "{{ NSDB_HOST }}"
      zooid: "1"

    - role: cassandra
      cluster_name: "midonet"
      listen_address: "{{ NSDB_HOST }}"
      seeds: "{{ NSDB_HOST }}"

    - role: midonet-midolman
      zookeeper_hosts: "{{ NSDB_HOST }}:2181"
      cassandra_hosts: "{{ NSDB_HOST }}"

    - role: midonet-api
      midonet_url: "http://{{ NSDB_HOST }}:8080/midonet-api"
      nova_api_hostname: "{{ NSDB_HOST }}"
      keystone_admin_token: "ADMIN_TOKEN"
      zookeeper_hosts: "{{ NSDB_HOST }}:2181"

    - role: midonet-cli
      nova_api_hostname: "{{ NSDB_HOST }}"


  tasks:
    - name: Install several packages needed and utilities
      action: apt pkg={{ item }} state=installed
      with_items:
        - nmap
        - tcpdump
        - wireshark
        - traceroute
        - quagga
        - screen
        - curl
        - htop
        - vim
        - python-pip
        - curl
        - dsniff
        - iperf
        - git
        - gcc
        - make
        - libpcap-dev
        - unzip
        - python-software-properties

    - name: Download mininet
      git: repo=https://github.com/mininet/mininet.git dest=/home/vagrant/mininet

    - name: Download mininet ripl
      git: repo=https://github.com/brandonheller/ripl.git dest=/home/vagrant/ripl

    - name: Download miniNext
      git: repo=https://github.com/USC-NSL/miniNExT.git dest=/home/vagrant/miniNExT

    - name: Download mininet bgp example
      git: repo=https://bitbucket.org/jvimal/bgp.git dest=/home/vagrant/bgp

    - name: Download masscan
      git: repo=https://github.com/robertdavidgraham/masscan

    - name: Install mininet
      command: /home/vagrant/mininet/util/install.sh -en

    - name: Test mininet
      sudo: yes
      command: mn --switch=lxbr --test pingall

